config/routes.rb
OnlineMusic::Application.routes.draw do

  resources :assets

  devise_for :users

  root :to => "home#index"

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  match "assets/get/:id" => "assets#get", :as => "download"

  match "/profile/index(.:format)" => "profile#index"

  match "/how/index(.:format)" => "how#index"

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  attr_accessible :user_id, :uploaded_file

  belongs_to :user

  #set up "uploaded_file" field as attached_file (using Paperclip)

  has_attached_file :uploaded_file,
                    :url => "/assets/get/:id",
                    :path => "public/:basename.:extension"

  validates_attachment_size :uploaded_file, :less_than => 10.megabytes
  validates_attachment_presence :uploaded_file

  validates_attachment_content_type :uploaded_file,
  :content_type => ['audio/mp3'],  :message => 'Uploading file must be .mp3 filetype!'

  def file_name
    uploaded_file_file_name
  end

  def file_size
    uploaded_file_file_size
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  validates :email, :presence => true, :uniqueness => true

  has_many :assets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @assets = current_user.assets
  end

  def new
    @asset = current_user.assets.new
  end

  def create
    @asset = current_user.assets.new(params[:asset])
    if @asset.save
      redirect_to root_url,  flash[:notice]  => "Successfully uploaded song."
    else
      render :action => 'new'
    end
  end

  def edit
    @asset = current_user.assets.find(params[:id])
  end

  def update
    @asset = current_user.assets.find(params[:id])
    if @asset.update_attributes(params[:asset])
      redirect_to root_url, flash[:notice]  => "Successfully updated song."
    else
      render :action => 'edit'
    end
  end

  def show
    @asset = current_user.assets.find(params[:id])
    @asset.destroy
    flash[:notice] = "Successfully deleted song."

    redirect_to root_url
  end


  #this action will let the users download the files (after a simple authorization check)
  def get
    asset = current_user.assets.find_by_id(params[:id])
    if asset
      send_file asset.uploaded_file.path, :type => asset.uploaded_file_content_type
    else
      flash[:error] = "This is not your song!"
      redirect_to root_url
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @assets = Asset.order("uploaded_file_file_name desc")
    end
  end
end

app/controllers/how_controller.rb
class HowController < ApplicationController
  protect_from_forgery
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    if user_signed_in?
      @assets = current_user.assets.order("uploaded_file_file_name desc")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/assets/_form.html.erb
<%= form_for @asset, :html => {:multipart => true} do |f| %>
    <%= f.error_messages %>
    <p>
      <%= f.label :uploaded_file, "File" %><br>
      <%= f.file_field :uploaded_file %>
    </p>
    <p><%= f.submit "Upload" %></p>
<% end %>

app/views/assets/edit.html.erb
<div class="head">
  <h1>Edit song</h1>
</div>

<%= render 'form' %>

<div class="links">
  <p><%= link_to "Back to List", root_url %></p>
</div>

app/views/assets/index.html.erb
<div class="head">
  <h1>Songs</h1>
</div>
<table>
  <tr>
    <th>Uploaded Files</th>
  </tr>
  <% for asset in @assets %>
      <tr>
        <td><%= link_to asset.file_name, download_url(asset)%></td>
        <td><%= link_to "Edit", edit_asset_path(asset) %></td>
        <td><%= link_to "Delete", asset, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
  <% end %>
</table>
<div class="links">
  <p><%= link_to "New Song", new_asset_path %></p>
</div>

app/views/assets/new.html.erb
<div class="head">
  <h1>Upload song</h1>
</div>

<%= render 'form' %>

<div class="links">
  <p><%= link_to "Back to List", root_url %></p>
</div>

app/views/assets/show.html.erb
<% title "Asset" %>

<p>
  <strong>User:</strong>
  <%= @asset.user_id %>
</p>

<p>
  <%= link_to "Edit", edit_asset_path(@asset) %> |
  <%= link_to "Destroy", @asset, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", assets_path %>
</p>

app/views/home/index.html.erb
<div class="head">
  <% unless user_signed_in? %>
      <h1>Welcome to onlineMusic</h1>
      <p>Listen to your music everywhere you are!</p><br/>
      <h3>Here is a song sample</h3>

      <audio controls>
        <source src="Kalimba.mp3" type="audio/mpeg">
      </audio>

      <div class="links">
        <br/>
        <%= link_to "How it works?", "/how/index" %>
      </div>

      </div>
      <% else %>

      <div class="head">
        <h1>All songs</h1>
      </div>

      <div id="menu">
        <ul id= "top_menu">
          <li><%= link_to "Profile", "/profile/index" %></li>
        </ul>
      </div>

      <div class="asset_list_header">
          <div class="file_name_header">File Name</div>
          <div class="file_size_header">Size</div>
          <div class="file_last_updated_header">Modified</div>
      </div>
      <div class="asset_list">



        <% @assets.each do |asset| %>
            <div class="asset_details file">
              <div class="file_name"><%= link_to asset.file_name, download_url(asset) %></div>
              <div class="file_size"><%= number_to_human_size(asset.file_size, :precision => 2) %></div>
              <div class="file_last_updated"><%= asset.uploaded_file_updated_at %></div>
             <!-- <div class="play_song"><a href="Basshunter_-_Every_Morning.mp3">Play song</a></div>   -->

              <div class="play_song"><%= link_to "Play song", asset.file_name %></div>

            </div>
        <% end %>


      </div>
  <% end %>


app/views/how/index.html.erb
<div class="head" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">

  <h2>Html 5 - Audio</h2>
  <p>Namestil sem gemfile Paperclip, ki omogoča nalaganje datotek za našo spletno aplikacijo. Ker gre pri tej aplikaciji za predvajanje glasbe more ta omejevati datoteke, ki jih uporabnik lahko naloži <i>(v mojem primeru so to .mp3 datoteke, ki se najpogosteje uporabljajo za predvajanje glasbe)</i>.</p>
  <p>V modelu <i>asset.rb</i> sem nastavil pogoj, da mora datoteka biti zahtevanega tipa. </p></br>
  <img src="/images/image1.PNG" alt="slika1"/></br>
  <p>Ker <i>audio</i> značka išče glasbo v t.i. <i>public</i> mapi, sem zaradi lažjega dela prav tako v modelu <i>asset.rb</i> nastavil, da se naložene glasbene datoteke shranijo v to mapo.</p>
  <img src="/images/image2.PNG" alt="slika2"/></br>
  <p>V primeru, da uporabnik hoče naložiti datoteko, ki ni .mp3 formata npr. sliko...</p>
  <img src="/images/image3.PNG" alt="slika3"/></br>
  <p>Mu vrne napako...</p>
  <img src="/images/image4.PNG" alt="slika4"/></br>
  <p>V nasprotnem primeru pa datoteko shrani v <i>public</i> mapo.</p>
  <img src="/images/image5.PNG" alt="slika5"/></br>
  <p>Za predvajanje glasbe imamo nato več možnosti. V mojem primeru sem uporabil dva primera in sicer z značko <i>audio</i> in z neposredno povezavo na skladbo <i>link_to</i>.</p>
  <img src="/images/image6.PNG" alt="slika6"/></br>
  <img src="/images/image7.PNG" alt="slika7"/></br>
  <p>V drugem primeru sem namesto neposrednega imena glasbe uporabil <i>asset.file_name</i> in sicer zaradi tega, ker lahko s tem uporabnik predvaja vse skladbe, ki so naložene na spletni strani. Ime tako dobim s pomočjo <i>asset_controllerja</i> v funkciji <i>get</i>.</p>
  <img src="/images/image8.PNG" alt="slika8"/></br>
  <p><b>Nik Bračič, 4. Tra</b></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "onlineMusic" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
  <div class="header_wrapper">
    <div id="login_user_status">
      <% if user_signed_in? %>
          <%= current_user.email  %>
          |
          <%= link_to 'Sign out', destroy_user_session_path %>
      <% else %>
          <em>Not Signed in.</em>
          <%= link_to 'Sign in', new_user_session_path%>
          or
          <%= link_to 'Sign up', new_user_registration_path%>
      <% end %>
    </div>
    <div class="logo">
      <%= link_to "onlineMusic", root_url %>
    </div>
    </div>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>

  </body>
</html>